### ISSUE TITLE
Why doesn't timezone-ii::rhel rewrite /etc/localtime?

### ISSUE THREAD

**Issue by laapsaap** [L2G/timezone-ii#14]
Why timezone-ii::rhel doesnt rewrite /etc/localtime? Only when I run linux-generic /etc/localtime gets updated.

Before we use chef, we did both. Updating clock and symlinking /etc/localtime to UTC

**Comment by L2G** [comment]
@laapsaap, please see whether the latest changes I pushed to the master branch help.

**Comment by obazoud** [comment]
Works fine here on Centos 6.5
Tested with master branch be26fef6da1ecb96e9830dc11302a3292d56bbb1
