### ISSUE TITLE
Format for /etc/timezone changes in Ubuntu 14.04 (precise)

### ISSUE THREAD

**Issue by avit** [L2G/timezone-ii#18]
Running this recipe on 14.04 causes this file to flip-flop on each run:

```
    - update content in file /etc/timezone from f0dcac to 1d403a
        --- /etc/timezone	2014-03-04 21:49:05.432858494 +0000
        +++ /tmp/chef-rendered-template20140304-8230-fp8r5m	2014-03-04 21:50:01.635255940 +0000
        @@ -1,2 +1,2 @@
        -Etc/UTC
        +UTC
```

This is with no attributes set, or with `defaults.tz  = 'UTC'`. Setting it to "Etc/UTC" silences it.

It only seems to happen on Ubuntu 14.04, not 12.04.

**Comment by L2G** [comment]
I found that this can happen with values other than "UTC", so I added something in that logs a warning if the recipe notices that the value stored in /etc/timezone changes after dpkg-reconfigure is run. I've also changed the default to "Etc/UTC" for the Debian family. Please let me know what you think of the changes.
