### ISSUE TITLE
Doesn't work on CentOS 7

### ISSUE THREAD

**Issue by indigo423** [L2G/timezone-ii#25]
If i try to set the "tz" parameter to a different timezone it is not applied on CentOS 7. With Ubuntu 14.04 the cookbook works as expected.

I got it to work by applying manually the pull request: #24 and set an additional parameter `use_symlink = true`

**Comment by L2G** [comment]
It looks like the issue with EL 7 is that the system utility for setting the timezone was replaced.

* EL 6: set `ZONE=timezone_name` in `/etc/sysconfig/clock`, then run `tzdata-update`
* EL 7: just run `timedatectl set-timezone timezone_name`

The reason why applying #24 worked is that it unconditionally called the `linux-generic` recipe, which replaces `/etc/localtime` on its own and is intended for systems that don't have their own utility for doing so. I don't want the cookbook to be managing `/etc/localtime` by default, although anyone could certainly call the `linux-generic` recipe directly if they prefer that approach.

As an aside, the `timedatectl` utility has nice, human-friendly output that explains the daylight-savings-time rules in effect for the current timezone, which I think is neato.

**Comment by indigo423** [comment]
Thanks for the detailed explanation. I'll give it a try.

**Comment by L2G** [comment]
Oh, and yes, I'm working on a fix for this as I type this. But if you don't see significant commits from me in the next day, I've probably given up on it and could use help. :smile_cat:

**Comment by L2G** [comment]
Oh, look at this, it's the same `timedatectl` as the `fedora` recipe uses. Maybe some refactoring is in order.
